targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: solufacil_mobile|lib/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: solufacil_mobile|lib/schema.graphql
